<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Check</name>
   <tag></tag>
   <elementGuidId>b035d41f-9a64-4227-a1fd-fb9735b9a4bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.i40dM4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Check&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c55f4af-4c96-4d15-b7c0-fcdc5f76cb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i40dM4</value>
      <webElementGuid>d2813971-95b5-45e5-87e6-f9f7a2a5c93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check</value>
      <webElementGuid>a3044bb8-6d87-433b-84ae-112cad193f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_39kFie N3De93 JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-8-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;row xO1qhs&quot;]/div[@class=&quot;col col-12-12&quot;]/div[@class=&quot;_98QWWQ&quot;]/div[@class=&quot;BvstzA&quot;]/div[@class=&quot;_5zD2Em _1UqGlq&quot;]/div[@class=&quot;guihks undefined&quot;]/div[@class=&quot;Ir+XS5 _5Owjac&quot;]/span[@class=&quot;i40dM4&quot;]</value>
      <webElementGuid>3e99baa8-54f8-4203-afe2-8422af94dfa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>bcd15ae6-e2cc-40c6-8cdd-79b6e1ef7775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/following::span[1]</value>
      <webElementGuid>2275732b-3071-444e-85b3-0c65b6531c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✕'])[3]/following::span[1]</value>
      <webElementGuid>a70c87d9-a182-4829-97d9-da627abeeaf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Saved Addresses'])[1]/preceding::span[1]</value>
      <webElementGuid>6076b310-84c9-45b4-befe-ab9b881ccc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent History'])[1]/preceding::span[3]</value>
      <webElementGuid>a0445b95-1269-40d4-9853-f9495e921112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check']/parent::*</value>
      <webElementGuid>806966d5-c7bc-476c-8d3e-d14b647cdc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>7aca81fb-ecde-42bb-bc0b-21baa74c8c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Check' or . = 'Check')]</value>
      <webElementGuid>c80f4989-8659-4795-8e1e-5dec9355820c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
