<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Check</name>
   <tag></tag>
   <elementGuidId>5d80d771-020f-42d4-a4b0-38497ff9bf02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.i40dM4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Check&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e449fbd-f215-49a6-bf6d-d54f81756c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i40dM4</value>
      <webElementGuid>2b74f7a3-065e-4180-8625-d92c07d92954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check</value>
      <webElementGuid>97ec06ee-b0b9-4308-bb99-f7629c237516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_39kFie N3De93 JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-8-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;row xO1qhs&quot;]/div[@class=&quot;col col-12-12&quot;]/div[@class=&quot;_98QWWQ&quot;]/div[@class=&quot;BvstzA&quot;]/div[@class=&quot;_5zD2Em _1UqGlq&quot;]/div[@class=&quot;guihks undefined&quot;]/div[@class=&quot;Ir+XS5 _5Owjac&quot;]/span[@class=&quot;i40dM4&quot;]</value>
      <webElementGuid>cffb11fe-14f4-42cd-b647-1cc5c9d11496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>9adc8080-77b3-4094-a8e3-146d1cc09b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/following::span[1]</value>
      <webElementGuid>a5a3ac88-ad3c-4f81-b381-dbdc98ab0592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✕'])[2]/following::span[1]</value>
      <webElementGuid>5c197b3e-541f-4499-bcad-e9bb2542af57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Saved Addresses'])[1]/preceding::span[1]</value>
      <webElementGuid>f6d824e9-d6e4-4fde-92b2-d73a9a244201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent History'])[1]/preceding::span[3]</value>
      <webElementGuid>a30c008d-473a-4a40-998e-b2d7c69376a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check']/parent::*</value>
      <webElementGuid>a0f47dc0-b144-48bb-be59-0afd14092865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>3acd0242-4bf3-425d-a4d9-b491d4f8deb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Check' or . = 'Check')]</value>
      <webElementGuid>20277073-ad4e-4a2b-bdde-7764b2e618d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
