<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Clock Speed_xTaogf</name>
   <tag></tag>
   <elementGuidId>327bf5cc-5b4f-44ce-89f8-b0a70ba734e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div[3]/div[2]/div[2]/div/div/a/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.rxRGiP > div._8z-Twi._4bzjfU > img.xTaogf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nothing-Phone3-CLP-PL-EB Nothing-Phone3-CLP-PL-EB&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9827d319-1dab-4ea1-91f7-b7117d51b980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xTaogf</value>
      <webElementGuid>9451282e-7fe4-4e58-9c40-667998b0c329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rukminim2.flixcart.com/fk-p-flap/844/140/image/16ec4521f22abe39.jpg?q=50</value>
      <webElementGuid>cfc6f8c6-6c31-43cf-9a47-17c206170e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nothing-Phone3-CLP-PL-EB</value>
      <webElementGuid>387af421-7887-4f91-8d7b-27f1b1686d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp col-10-12&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;Xx1qdf pfZzx5&quot;]/div[@class=&quot;edj-gW&quot;]/a[@class=&quot;rxRGiP&quot;]/div[@class=&quot;_8z-Twi _4bzjfU&quot;]/img[@class=&quot;xTaogf&quot;]</value>
      <webElementGuid>5b803ef9-dce8-4658-ad55-c06578e0781b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div[3]/div[2]/div[2]/div/div/a/div/img[2]</value>
      <webElementGuid>503f0a10-6e1e-4b6a-9b8f-fc2aa69d01ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Nothing-Phone3-CLP-PL-EB'])[2]</value>
      <webElementGuid>62b51da5-8bbe-42fb-ba00-e16792e0ddbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img[2]</value>
      <webElementGuid>3dd122fb-cf09-44b5-9d3b-0e50895a4ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rukminim2.flixcart.com/fk-p-flap/844/140/image/16ec4521f22abe39.jpg?q=50' and @alt = 'Nothing-Phone3-CLP-PL-EB']</value>
      <webElementGuid>2fc6649a-b2c9-4661-90f4-7e637c00f0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
