<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plus_q</name>
   <tag></tag>
   <elementGuidId>117c8dc8-05b2-441e-8551-1034a28d2c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='q']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;q&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search for products, brands and more&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d05773d5-941f-4c90-86b2-17aa33681832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zDPmFV</value>
      <webElementGuid>56aa211c-7fb1-4535-b0ec-6a4effcadee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c0deca7-f559-412d-bd50-7616ac823790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for products, brands and more</value>
      <webElementGuid>67e7e38a-4a55-4c02-88c3-0e34a705505b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>63450c0b-ea4d-4643-9dbf-f6bcaa7e8ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fb30664d-536b-4299-8d00-97fb02d5c11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for products, brands and more</value>
      <webElementGuid>88562031-d3cb-47f4-b071-60dda91c4300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;krHvwW&quot;]/div[@class=&quot;J+HqMZ&quot;]/div[@class=&quot;Ja1j8k&quot;]/div[@class=&quot;kRd8Cs&quot;]/form[@class=&quot;Hy6F9O header-form-search&quot;]/div[@class=&quot;col-12-12 BnmXvV&quot;]/div[@class=&quot;MoPwtI&quot;]/input[@class=&quot;zDPmFV&quot;]</value>
      <webElementGuid>fc915ebe-b217-42bc-8bed-99ca671ae5c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='q']</value>
      <webElementGuid>dbb8aae8-0d2c-4bc5-bbd3-cbd8e73462c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[2]/form/div/div/input</value>
      <webElementGuid>e6a1a51c-8974-442d-b0c8-fc6090c96345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>af1ed7c4-8538-4234-a7f8-641efa7b29c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Search for products, brands and more' and @name = 'q' and @placeholder = 'Search for products, brands and more']</value>
      <webElementGuid>1c94defe-d844-4b37-bbbe-58b2a524b593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
