<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_boAt Rockerz 430 w Beast Mode(40ms Low La_69fb40</name>
   <tag></tag>
   <elementGuidId>6e0e5e10-dbcd-4f57-9dc8-f2321d8ecd36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[3]/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4ff88e4-a046-4615-a7fb-e99950034dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wjcEIp</value>
      <webElementGuid>ec33ac90-f557-444d-84af-3f2bff053b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS Playback &amp; 40MM Drivers Bluetooth</value>
      <webElementGuid>580f3e37-4ae9-4247-926b-ee363ec7b07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8dcd270e-f310-4126-8554-dd3fb05fd46e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>5ac3d940-db3a-413c-a1ff-429298068f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/boat-rockerz-430-w-beast-mode-40ms-low-latency-40hrs-playback-40mm-drivers-bluetooth/p/itma5e58807a8450?pid=ACCH44E54RMWWH28&amp;lid=LSTACCH44E54RMWWH28XHSLXA&amp;marketplace=FLIPKART&amp;store=0pm&amp;srno=b_1_5&amp;otracker=browse&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;fm=organic&amp;iid=c3d3a179-8d0e-4232-bf9a-4e4f9b9a528f.ACCH44E54RMWWH28.SEARCH&amp;ppt=browse&amp;ppn=browse&amp;ssid=586z8429fk0000001751428260387</value>
      <webElementGuid>a147b5a0-80fd-4f7f-a41b-8efe6ca4239d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...</value>
      <webElementGuid>df8a6144-9d89-41c2-9a75-791999181677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_75nlfW&quot;]/div[1]/div[@class=&quot;slAVV4&quot;]/a[@class=&quot;wjcEIp&quot;]</value>
      <webElementGuid>ca434453-fe36-445b-b3f9-08bfc53a009b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[3]/div/div/div/a[2]</value>
      <webElementGuid>892b8398-0c0a-488c-b6a2-7b840ce409e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...')]</value>
      <webElementGuid>3d77d94a-9693-4898-9869-f6cc38755e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[4]/following::a[2]</value>
      <webElementGuid>40e760e1-429a-46b8-8677-a66289689716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only few left'])[2]/following::a[2]</value>
      <webElementGuid>e2c56f80-5f92-4da8-ab1b-e5a7795ad42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold Blue, On the Ear'])[1]/preceding::a[1]</value>
      <webElementGuid>ac748cb2-3756-4e01-8d09-2ff6c3cf98e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(25,163)'])[1]/preceding::a[1]</value>
      <webElementGuid>77759e27-647a-4dd9-9cbc-cabfeccda903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...']/parent::*</value>
      <webElementGuid>5cd1287f-bb10-4988-8fb7-df7eb615e4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/boat-rockerz-430-w-beast-mode-40ms-low-latency-40hrs-playback-40mm-drivers-bluetooth/p/itma5e58807a8450?pid=ACCH44E54RMWWH28&amp;lid=LSTACCH44E54RMWWH28XHSLXA&amp;marketplace=FLIPKART&amp;store=0pm&amp;srno=b_1_5&amp;otracker=browse&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;fm=organic&amp;iid=c3d3a179-8d0e-4232-bf9a-4e4f9b9a528f.ACCH44E54RMWWH28.SEARCH&amp;ppt=browse&amp;ppn=browse&amp;ssid=586z8429fk0000001751428260387')])[2]</value>
      <webElementGuid>8c075214-9f6c-4507-9b88-ff91130845d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a[2]</value>
      <webElementGuid>8df8a070-222f-4660-9e15-c435688385cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS Playback &amp; 40MM Drivers Bluetooth' and @href = '/boat-rockerz-430-w-beast-mode-40ms-low-latency-40hrs-playback-40mm-drivers-bluetooth/p/itma5e58807a8450?pid=ACCH44E54RMWWH28&amp;lid=LSTACCH44E54RMWWH28XHSLXA&amp;marketplace=FLIPKART&amp;store=0pm&amp;srno=b_1_5&amp;otracker=browse&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;fm=organic&amp;iid=c3d3a179-8d0e-4232-bf9a-4e4f9b9a528f.ACCH44E54RMWWH28.SEARCH&amp;ppt=browse&amp;ppn=browse&amp;ssid=586z8429fk0000001751428260387' and (text() = 'boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...' or . = 'boAt Rockerz 430 w/ Beast Mode(40ms Low Latency),40HRS ...')]</value>
      <webElementGuid>7af97b32-1621-4765-9366-a7b1b7912bba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
