<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_boAt Rockerz 450 w 40mm Drivers, 15 HRS P_12ca7e</name>
   <tag></tag>
   <elementGuidId>0e343d18-dd52-4164-9710-56a44285b833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wjcEIp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b2b2b56-c01e-4786-a477-f4ba032465c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth</value>
      <webElementGuid>36b2a1a8-6e7f-4dc2-a802-79630aeee3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wjcEIp</value>
      <webElementGuid>988d526f-1621-4971-a141-8c64b9403cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>20d37664-5bcd-425c-8daf-a9471c4c5c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>fb32243f-05f2-420b-a930-c5d70a9fe876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/boat-rockerz-450-w-40mm-drivers-15-hrs-playback-soft-padded-earcups-bluetooth/p/itmb3a87c939ee82?pid=ACCFQKK85DSZSDHC&amp;lid=LSTACCFQKK85DSZSDHCFEJLYY&amp;marketplace=FLIPKART&amp;fm=productRecommendation%2Fsimilar&amp;iid=R%3As%3Bp%3AACCH44E54RMWWH28%3Bl%3ALSTACCH44E54RMWWH28XHSLXA%3Bpt%3App%3Buid%3Acbfd6f9f-56f7-11f0-8db0-532aae0635fd%3B.ACCFQKK85DSZSDHC&amp;ppt=pp&amp;ppn=pp&amp;ssid=586z8429fk0000001751428260387&amp;otracker=pp_reco_Similar+Products_1_37.productCard.PMU_HORIZONTAL_boAt+Rockerz+450+w%252F+40mm+Drivers%252C+15+HRS+Playback%252C+Soft+Padded+Earcups+Bluetooth_ACCFQKK85DSZSDHC_productRecommendation%2Fsimilar_0&amp;otracker1=pp_reco_PINNED_productRecommendation%2Fsimilar_Similar+Products_GRID_productCard_cc_1_NA_view-all&amp;cid=ACCFQKK85DSZSDHC</value>
      <webElementGuid>80e5f5ad-6af2-4781-9326-73c3a401601c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...</value>
      <webElementGuid>50017012-495e-4524-a9bf-f58b3e3f4fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_39kFie N3De93 JxFEK3 _48O0EI&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;Pg+ADy card-tile&quot;]/div[@class=&quot;pq8uUv&quot;]/div[@class=&quot;NZWrVR&quot;]/div[@class=&quot;fOaS6u WccAh0&quot;]/div[@class=&quot;_9CpqQc&quot;]/div[@class=&quot;a7hc-p WccAh0&quot;]/div[@class=&quot;N27L5l&quot;]/div[@class=&quot;Ip5wZF ZN53sF&quot;]/div[@class=&quot;slAVV4 qt3Pmj&quot;]/div[1]/div[1]/a[@class=&quot;wjcEIp&quot;]</value>
      <webElementGuid>6417b490-8e6c-4369-817c-082e05e2a4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>ec8c80bb-04fc-4568-9cc1-f76745053f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...')]</value>
      <webElementGuid>2d36856c-c0d8-4166-b4dd-0211a1eff544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Similar Products'])[1]/following::a[2]</value>
      <webElementGuid>a8040a47-7e58-4555-b030-b7c6ef2bd432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safe and Secure Payments.Easy returns.100% Authentic products.'])[1]/following::a[2]</value>
      <webElementGuid>e4cd5e1e-a845-4773-927f-2038d9d093e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3,91,404)'])[1]/preceding::a[1]</value>
      <webElementGuid>53446eb8-1320-49ce-9386-0647a78c67d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,399'])[1]/preceding::a[1]</value>
      <webElementGuid>ecdcbc1e-4a8e-4989-900f-a6fa8ce8de25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...']/parent::*</value>
      <webElementGuid>02c8e7f6-b0ed-4752-8a2f-229a641a38eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/boat-rockerz-450-w-40mm-drivers-15-hrs-playback-soft-padded-earcups-bluetooth/p/itmb3a87c939ee82?pid=ACCFQKK85DSZSDHC&amp;lid=LSTACCFQKK85DSZSDHCFEJLYY&amp;marketplace=FLIPKART&amp;fm=productRecommendation%2Fsimilar&amp;iid=R%3As%3Bp%3AACCH44E54RMWWH28%3Bl%3ALSTACCH44E54RMWWH28XHSLXA%3Bpt%3App%3Buid%3Acbfd6f9f-56f7-11f0-8db0-532aae0635fd%3B.ACCFQKK85DSZSDHC&amp;ppt=pp&amp;ppn=pp&amp;ssid=586z8429fk0000001751428260387&amp;otracker=pp_reco_Similar+Products_1_37.productCard.PMU_HORIZONTAL_boAt+Rockerz+450+w%252F+40mm+Drivers%252C+15+HRS+Playback%252C+Soft+Padded+Earcups+Bluetooth_ACCFQKK85DSZSDHC_productRecommendation%2Fsimilar_0&amp;otracker1=pp_reco_PINNED_productRecommendation%2Fsimilar_Similar+Products_GRID_productCard_cc_1_NA_view-all&amp;cid=ACCFQKK85DSZSDHC')])[2]</value>
      <webElementGuid>c45a3646-e586-4ccc-bf2c-32f6eb15b480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>9ada19cc-3745-4913-8eef-e53ba879fec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Earcups Bluetooth' and @href = '/boat-rockerz-450-w-40mm-drivers-15-hrs-playback-soft-padded-earcups-bluetooth/p/itmb3a87c939ee82?pid=ACCFQKK85DSZSDHC&amp;lid=LSTACCFQKK85DSZSDHCFEJLYY&amp;marketplace=FLIPKART&amp;fm=productRecommendation%2Fsimilar&amp;iid=R%3As%3Bp%3AACCH44E54RMWWH28%3Bl%3ALSTACCH44E54RMWWH28XHSLXA%3Bpt%3App%3Buid%3Acbfd6f9f-56f7-11f0-8db0-532aae0635fd%3B.ACCFQKK85DSZSDHC&amp;ppt=pp&amp;ppn=pp&amp;ssid=586z8429fk0000001751428260387&amp;otracker=pp_reco_Similar+Products_1_37.productCard.PMU_HORIZONTAL_boAt+Rockerz+450+w%252F+40mm+Drivers%252C+15+HRS+Playback%252C+Soft+Padded+Earcups+Bluetooth_ACCFQKK85DSZSDHC_productRecommendation%2Fsimilar_0&amp;otracker1=pp_reco_PINNED_productRecommendation%2Fsimilar_Similar+Products_GRID_productCard_cc_1_NA_view-all&amp;cid=ACCFQKK85DSZSDHC' and (text() = 'boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...' or . = 'boAt Rockerz 450 w/ 40mm Drivers, 15 HRS Playback, Soft Padded Ea...')]</value>
      <webElementGuid>46a722cf-f1ad-4073-ae60-33a8eb3cbff0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
