<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bestseller_DByuf4</name>
   <tag></tag>
   <elementGuidId>b64666f2-117e-4216-8243-a1d1e4cc22aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.DByuf4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Bestseller Nothing Phone (3a) (White, 128 GB) Add to Compare Nothing Phone (3a) (White, 128 GB) 4.5 24,945 Ratings &amp; 2,263 Reviews • 8 GB RAM | 128 GB ROM • 43.66 cm (17.19 cm) Full HD+ Display • 50MP (Main) + 50MP (2X Tele Photo) + 8MP (Ultra-Wide) | 32MP Front Camera • 5000 mAh Battery • 7s Gen3 Processor • 1 Year Manufacturing Warranty ₹24,999 ₹27,999 10% off Only few left Upto ₹19,000 Off on Exchange&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d92b3a6-c0e4-48ec-99a3-0f016dbd1800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>0bebed3b-9475-493b-b5f8-4704ea8d2638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DByuf4</value>
      <webElementGuid>0c9d9fc7-fee1-4a26-bee2-19ee292a1307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nothing Phone (3a) (White, 128 GB)</value>
      <webElementGuid>d762e1ac-a385-47c7-8719-6b6dab8e0823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/e/l/m/-original-imahcfcfhxrf5hzg.jpeg?q=70</value>
      <webElementGuid>9ab8146a-290e-462a-ba60-3f6be920eb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;nt6sNV JxFEK3 _48O0EI&quot;]/div[@class=&quot;DOjaWF YJG4Cf&quot;]/div[@class=&quot;DOjaWF gdgoEp&quot;]/div[@class=&quot;cPHDOP col-12-12&quot;]/div[@class=&quot;_75nlfW&quot;]/div[1]/div[@class=&quot;tUxRFH&quot;]/a[@class=&quot;CGtC98&quot;]/div[@class=&quot;Otbq5D&quot;]/div[@class=&quot;yPq5Io&quot;]/div[1]/div[@class=&quot;_4WELSP&quot;]/img[@class=&quot;DByuf4&quot;]</value>
      <webElementGuid>e3a3f855-253e-45d6-99e6-74bc4d814bdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div/div/img</value>
      <webElementGuid>c1a0cbbc-2ed8-43aa-ad62-3290be070159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Nothing Phone (3a) (White, 128 GB)']</value>
      <webElementGuid>ca296cbd-11ad-43ac-9943-a131319e3d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/img</value>
      <webElementGuid>4a8b5bc6-a5da-4715-a332-810d6e0fc371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Nothing Phone (3a) (White, 128 GB)' and @src = 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/e/l/m/-original-imahcfcfhxrf5hzg.jpeg?q=70']</value>
      <webElementGuid>91b88673-0092-4eb3-aa6e-b4dcecbeeb82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
