<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>2218dc26-5550-409f-ad14-3c778693be88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'All')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._3490ry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;All&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96f10648-78c5-4c68-81c1-ed8ef031e8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_8c7ac5b4-c353-40f6-806c-32d11eae7fc8_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD</value>
      <webElementGuid>29c5be1e-97fe-48e5-bbd3-13b66d9fb1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3490ry</value>
      <webElementGuid>991e9ffc-d960-4222-8939-5bee6ab0c518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>a205dbdc-7a4c-4d45-96a8-b098392313f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;useInterFont en-fonts-loaded&quot;]/body[1]/div[@class=&quot;_1UgUYI _2eN8ye&quot;]/div[@class=&quot;_31z7R_&quot;]/object[1]/a[@class=&quot;_3490ry&quot;]</value>
      <webElementGuid>61902a7a-c142-478c-bca5-3d5805f39a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'All')])[2]</value>
      <webElementGuid>cb0e94cb-1605-4582-aea0-a2c3bc9526ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tablets'])[1]/following::a[1]</value>
      <webElementGuid>7d97b7d8-44a2-42a7-bc2e-4bfe14ed4a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bluetooth Headphones'])[1]/preceding::a[1]</value>
      <webElementGuid>360296ad-f304-4ebe-8c5d-1a283b3ffdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wired Headphones'])[1]/preceding::a[2]</value>
      <webElementGuid>23d39f74-12ed-40b8-b5e0-e51144ce70de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All']/parent::*</value>
      <webElementGuid>f71584b9-0c0d-40a5-8c07-a898ce6be182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_8c7ac5b4-c353-40f6-806c-32d11eae7fc8_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD')]</value>
      <webElementGuid>26d94a84-cdc0-4556-8e0b-cfa92b9fddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/object/a</value>
      <webElementGuid>319f137f-9dae-4421-b08e-8be440564afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/audio-video/pr?sid=0pm&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_8c7ac5b4-c353-40f6-806c-32d11eae7fc8_1_372UD5BXDFYS_MC.9JGNW7M0TUHD&amp;otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics~Audio~All_9JGNW7M0TUHD&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&amp;cid=9JGNW7M0TUHD' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>5b1b2fe2-bc29-4df0-8c69-7b36c649ba60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
